version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore dotnet-core-hello-world.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o dotnet-core-hello-world.csproj
